language: java
install: true
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "squat-team"
    token:
      secure: "IZow8aaKfotJq6Y0HXz/fqlX392GAWgfwabzirAFBQGvo+Lq/Hr+Efwko8eh9N2s3cCm4uQ68Tulitu0PSJZ+cefRBald27Ib869vtUR9MSZA2PTN81Jj0dvqN5tv+jolyNIqNGSZzg9XbEsi4BgxZ+255SsQvzaDkkKSlfckouh+SiZ7sbtZIcHLMMhAVytNLCS3tiYVB81LkBza70PjS2DcdSbdHgMatQ+ARIkFApA4qA+2sDzemQXY+RpDHvxrCO65ONvjBnURNN/oxQuJTFva6Uq8ONE3375JogIYnqjBsB+Zx28bLNIfU+T1/21Tlbzpxhy27nW+VoD+lsxSn9FcPH+xvXS39XlqHZMJqUWAIlp/Yn9GXHAHYhBr9CZdT26Ush2gJVAGb0RIYdwhdiBICm7lSLdPu/DvZUhL8cmUUNnE3CX5l8lM0S5hInrzo4mVSzCBwZP8N7hg0MOR+d5dJwlp5cEEQD9E8rn/B0mT3eA7ZLAFSSZKPcFMiukfxHn5eym8DWhwKlLQQxZgRQbUYF1NnO2LpKezXU01odJLYDwhw6CNlVOWtlils/GKA25AEga7HEAFccYERbTMhP1MEkP8/EkJDUTRM0O6E5x8yNnsibLmZMmPQNE0R9NA73yH5YnIQDNZ24TWFP59pXT7UdXSP1hD/rTsb4r10c="
script:
- mvn install:install-file -Dfile=SquatVis/libs/callgraph-1.0.0.jar -DgroupId=io.github.squat_team.callgraph -DartifactId=callgraph -Dversion=1.0.0 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/org.eclipse.emf.cdo_4.4.1.v20151007-1653.jar -DgroupId=org.eclipse.emf -DartifactId=cdo -Dversion=4.4.1 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/org.eclipse.emf.common_2.10.1.v20150123-0348.jar -DgroupId=org.eclipse.emf -DartifactId=common -Dversion=2.10.1 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/org.eclipse.emf.ecore_2.10.2.v20150123-0348.jar -DgroupId=org.eclipse.emf -DartifactId=ecore -Dversion=2.10.2 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/org.eclipse.ocl_3.5.0.v20150521-1211.jar -DgroupId=org.eclipse.ocl -DartifactId=ocl -Dversion=3.5.0 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/org.eclipse.ocl.common_1.3.0.v20150519-0914.jar -DgroupId=org.eclipse.ocl -DartifactId=common -Dversion=1.3.0 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/org.eclipse.ocl.ecore_3.5.0.v20150525-1635.jar -DgroupId=org.eclipse.ocl -DartifactId=ecore -Dversion=3.5.0 -Dpackaging=jar
- mvn install:install-file -Dfile=SquatVis/libs/palladio-environment-0.6.3-SNAPSHOT.jar -DgroupId=de.fakeller.palladio-headless -DartifactId=palladio-environment -Dversion=0.6.3-SNAPSHOT -Dpackaging=jar
- mvn -q -B -f SquatVisToolConnector/pom.xml clean install sonar:sonar
- mvn -q -B -f SquatVis/pom.xml clean install sonar:sonar
deploy:
  provider: releases
  api_key:
    secure: G/OgzkQG3+e5j+XvvO155yVSUjE2Wy6EvZfdLpgCJIyWr7qvao7RY7oGn8PE6SjOysIMTxPdRzKaIntA65+i7Xf2tMJIWUCC4v+JTek6DjuenR5yb8xNkPFZ7IJSqTuNl2DGm0pLczOb1HzaeAgyV2e2sKL407cLo81jkqZk+lsYbNNisGyshFtcvaOxBkrzfFLQsYY93lDgqgLZemBl760SPBD/tYi/hypk8JKm1/8V3VUPbMy2d2MwQnZ7krzpyOonxxBCxAI/yTVQE7HN33xEG3TBvPmu6LeLdknmxXi3NkYDa4ROkABZHoyTyGPjuRT8vlFWpe8GsIGoODONzOcVqrbNBu9xWBm5HDSA1Rp5yT4wktetiVhzbTqKTeyccnlNW9yKE1rPZwzKL1U7KgsTDtly8xAD+eDRRxObz+RdSob8GC9mMDM2f9XNxl4SU8U1FT4cR9nXVHcf7W19nE2qS9vJjHhJAS/wv971OINX/Yam4lypjFEN2HwnLEI/fQTL3CPutc5G7uS+AvHhQZwyBH6MC8wINQlWC6ai6u26vvQOZ93e+HEM2uiVXRmBzZ9fydPQ+qXVqxRes3WHmWlEWxGZXyQVCNnYMvLd4B+bFToNgtgu7AN/ss8UJlZAn6Rl6/m8ShLiDrZQ2N+feGr+3vaq9glKZlqwY4B5Vgc=
  skip_cleanup: true
  file_glob: true
  file: 
  - $TRAVIS_BUILD_DIR/SquatVis/target/SquatVis*.war
  - $TRAVIS_BUILD_DIR/SquatVisToolConnector/target/SquatVisToolConnector*.jar
  on:
    repo: SQuAT-Team/squat-vis
    tags: true